import React, { useState, useEffect } from 'react';
import Button from './Button';
import { Loader2, AlertTriangle, ChevronRight, ChevronLeft, Lock, TrendingUp, Activity, Terminal } from 'lucide-react';

interface DiagnosticProps {
  onBookAudit: () => void;
  onBack: () => void;
}

// Data Structures
type Question = {
  id: string;
  text: string;
  options: { label: string; value: any; scorePenalty?: number }[];
};

const QUESTIONS: Question[] = [
  {
    id: 'scope',
    text: 'Operational Scope (Business Model)',
    options: [
      { label: 'Service / Agency', value: 'agency' },
      { label: 'SaaS / Tech', value: 'saas' },
      { label: 'E-Commerce', value: 'ecom' },
      { label: 'Traditional / Brick & Mortar', value: 'trad' }
    ]
  },
  {
    id: 'revenue',
    text: 'Revenue Velocity (Current Monthly)',
    options: [
      { label: '< £10k', value: 10000 },
      { label: '£10k - £50k', value: 50000 },
      { label: '£50k - £200k', value: 200000 },
      { label: '£200k+', value: 250000 }
    ]
  },
  {
    id: 'team',
    text: 'Team Architecture (Size)',
    options: [
      { label: 'Just Me', value: 1 },
      { label: 'Small Team (2-5)', value: 3 },
      { label: 'Growing (6-20)', value: 12 },
      { label: 'Scaling (20+)', value: 30 }
    ]
  },
  {
    id: 'friction',
    text: 'The Friction Metric (Hours/week/person lost to admin)',
    options: [
      { label: '< 5 Hours', value: 2, scorePenalty: 0 },
      { label: '5 - 10 Hours', value: 7, scorePenalty: 10 },
      { label: '10 - 20 Hours', value: 15, scorePenalty: 20 },
      { label: '20+ Hours', value: 25, scorePenalty: 30 }
    ]
  },
  {
    id: 'stack',
    text: 'Stack Integrity (Tech Connectivity)',
    options: [
      { label: 'Scattergun (Disconnected)', value: 'disconnected', scorePenalty: 15 },
      { label: 'Patchwork (Loose Zaps)', value: 'patchwork', scorePenalty: 5 },
      { label: 'Integrated (Systemised)', value: 'integrated', scorePenalty: 0 }
    ]
  },
  {
    id: 'reallocation',
    text: 'Capacity Reallocation (Where would reclaimed hours go?)',
    options: [
      { label: 'Sales / Outreach', value: 'sales' },
      { label: 'Client Delivery', value: 'delivery' },
      { label: 'Marketing / Content', value: 'marketing' },
      { label: 'Product Dev', value: 'product' },
      { label: 'Retention', value: 'retention' }
    ]
  },
  {
    id: 'impact',
    text: 'Revenue Impact (Revenue generated by 1 hour of high-value work?)',
    options: [
      { label: '£0 - £25', value: 15 },
      { label: '£25 - £50', value: 35 },
      { label: '£50 - £100', value: 75 },
      { label: '£100 - £250', value: 175 },
      { label: '£250+', value: 300 }
    ]
  }
];

const Diagnostic: React.FC<DiagnosticProps> = ({ onBookAudit, onBack }) => {
  const [stage, setStage] = useState<'intro' | 'questions' | 'processing' | 'gate' | 'results'>('intro');
  const [currentQIndex, setCurrentQIndex] = useState(0);
  
  // Store answers mapped by Question ID
  const [answers, setAnswers] = useState<Record<string, any>>({});
  const [penalties, setPenalties] = useState<number[]>([]);
  
  const [processingText, setProcessingText] = useState('Initialising...');
  
  // Lead Capture Form
  const [leadForm, setLeadForm] = useState({ name: '', email: '', url: '' });
  const [isFormValid, setIsFormValid] = useState(false);
  const [touched, setTouched] = useState({ email: false, url: false });

  // Metrics for display
  const [metrics, setMetrics] = useState({
    operationalWaste: 0,
    revenueUplift: 0,
    totalLeakage: 0,
    efficiencyScore: 100,
    annualLeakage: 0
  });

  // Animated Counter Logic
  const [displayLeakage, setDisplayLeakage] = useState(0);

  // Validation Regex
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  // Matches optional protocol, domain name (with dots/hyphens), dot, and at least 2 char TLD
  const urlRegex = /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,})([\/\w \.-]*)*\/?$/i;

  // Validate form effects
  useEffect(() => {
    const isEmailValid = emailRegex.test(leadForm.email);
    const isUrlValid = urlRegex.test(leadForm.url);
    const isNameValid = leadForm.name.trim().length > 0;

    setIsFormValid(isEmailValid && isUrlValid && isNameValid);
  }, [leadForm]);

  useEffect(() => {
    if (stage === 'results') {
      let start = 0;
      const end = metrics.totalLeakage;
      const duration = 2000;
      const incrementTime = 20;
      const step = end / (duration / incrementTime);

      const timer = setInterval(() => {
        start += step;
        if (start >= end) {
          setDisplayLeakage(end);
          clearInterval(timer);
        } else {
          setDisplayLeakage(Math.floor(start));
        }
      }, incrementTime);
      return () => clearInterval(timer);
    }
  }, [stage, metrics.totalLeakage]);

  const handleOptionSelect = (qId: string, value: any, penalty?: number) => {
    setAnswers(prev => ({ ...prev, [qId]: value }));
    if (penalty) {
      setPenalties(prev => [...prev, penalty]);
    }

    if (currentQIndex < QUESTIONS.length - 1) {
      setCurrentQIndex(prev => prev + 1);
    } else {
      startProcessing();
    }
  };

  const startProcessing = () => {
    setStage('processing');
    const texts = [
      'Accessing Global Benchmarks...',
      'Calculating Opportunity Cost...',
      'Analysing Stack Integrity...',
      'Compiling Financial Model...'
    ];
    let i = 0;
    const interval = setInterval(() => {
      setProcessingText(texts[i]);
      i++;
      if (i >= texts.length) {
        clearInterval(interval);
        calculateMetrics(); // Calculate before showing gate
        setStage('gate'); 
      }
    }, 800);
  };

  const calculateMetrics = () => {
    // We access state 'answers' directly here. In a real strict environment we'd use a ref or pass values.
    // Given the flow, answers are set before this runs.
    
    const teamSize = answers['team'] || 1;
    const frictionHours = answers['friction'] || 2;
    const revenueImpact = answers['impact'] || 15;
    
    // Step A: Operational Waste (Team * Hours * £35 * 4 weeks)
    const opWaste = teamSize * frictionHours * 35 * 4;
    
    // Step B: Revenue Uplift (Team * Hours * RevImpact * 4 weeks)
    const uplift = teamSize * frictionHours * revenueImpact * 4;
    
    // Step C: Total
    const total = opWaste + uplift;
    
    // Efficiency Score
    const totalPenalty = penalties.reduce((a, b) => a + b, 0);
    const score = Math.max(0, 100 - totalPenalty);

    setMetrics({
      operationalWaste: opWaste,
      revenueUplift: uplift,
      totalLeakage: total,
      efficiencyScore: score,
      annualLeakage: total * 12
    });
  };

  const handleGateSubmit = () => {
    if (!isFormValid) {
      setTouched({ email: true, url: true });
      return;
    }
    
    // POST to Google Sheets via Apps Script
    const endpoint = import.meta.env.VITE_GOOGLE_SHEETS_ENDPOINT;
    if (endpoint) {
      fetch(endpoint, {
        method: 'POST',
        mode: 'no-cors', // Required for Google Apps Script
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          timestamp: new Date().toISOString(),
          name: leadForm.name,
          email: leadForm.email,
          url: leadForm.url,
          scope: answers['scope'] || '',
          revenue: answers['revenue'] || '',
          team: answers['team'] || '',
          friction: answers['friction'] || '',
          stack: answers['stack'] || '',
          reallocation: answers['reallocation'] || '',
          impact: answers['impact'] || '',
          operationalWaste: metrics.operationalWaste,
          revenueUplift: metrics.revenueUplift,
          totalLeakage: metrics.totalLeakage,
          efficiencyScore: metrics.efficiencyScore,
          annualLeakage: metrics.annualLeakage
        })
      }).catch(err => console.error('Lead capture error:', err));
    } else {
      console.log("LEAD CAPTURED (no endpoint configured):", leadForm, metrics);
    }
    
    setStage('results');
  };

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP', maximumFractionDigits: 0 }).format(val);
  };

  return (
    <div className="min-h-screen bg-void flex items-center justify-center p-4 relative overflow-hidden blueprint-grid">
      {/* Background Decor */}
      <div className="absolute top-0 left-0 w-full h-full pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-mint-start rounded-full blur-[150px] opacity-10"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-red-500 rounded-full blur-[150px] opacity-5"></div>
      </div>

      {/* Back Link */}
      <button 
        onClick={onBack}
        className="absolute top-6 left-6 flex items-center gap-2 text-gray-500 hover:text-mint-start transition-colors font-mono text-sm z-50 cursor-pointer"
      >
        <ChevronLeft size={16} /> ABORT SEQUENCE
      </button>

      {/* Main Container */}
      <div className="relative w-full max-w-2xl glass-panel border-2 border-mint-start p-8 md:p-12 shadow-[0_0_50px_rgba(160,240,230,0.1)] transition-all duration-500 min-h-[600px] flex flex-col justify-center">
        
        {/* Corner Brackets */}
        <div className="absolute top-0 left-0 w-8 h-8 border-t-4 border-l-4 border-mint-start -translate-x-1 -translate-y-1 z-20"></div>
        <div className="absolute top-0 right-0 w-8 h-8 border-t-4 border-r-4 border-mint-start translate-x-1 -translate-y-1 z-20"></div>
        <div className="absolute bottom-0 left-0 w-8 h-8 border-b-4 border-l-4 border-mint-start -translate-x-1 translate-y-1 z-20"></div>
        <div className="absolute bottom-0 right-0 w-8 h-8 border-b-4 border-r-4 border-mint-start translate-x-1 translate-y-1 z-20"></div>

        {/* STATE 1: INTRO */}
        {stage === 'intro' && (
          <div className="text-center animate-in fade-in zoom-in duration-500">
            <div className="inline-block p-4 border-2 border-black rounded-full bg-mint-start/10 mb-6">
              <TrendingUp className="w-12 h-12 text-mint-start" />
            </div>
            <h1 className="font-display font-bold text-4xl md:text-5xl mb-4 tracking-tight text-white">
              90-SECOND EFFICIENCY DIAGNOSTIC
            </h1>
            <p className="font-sans text-gray-400 text-lg mb-10 max-w-md mx-auto leading-relaxed">
              Identify hidden revenue leaks and quantify your operational friction in under 90 seconds.
            </p>
            <Button onClick={() => setStage('questions')} className="w-full md:w-auto text-lg px-12 py-4">
              INITIATE SCAN
            </Button>
          </div>
        )}

        {/* STATE 2: QUESTIONS */}
        {stage === 'questions' && (
          <div className="animate-in slide-in-from-right duration-300">
            {/* Progress Bar */}
            <div className="flex justify-between text-xs font-mono text-mint-start mb-2 uppercase tracking-widest">
              <span>Node {currentQIndex + 1}</span>
              <span>{QUESTIONS.length} Total</span>
            </div>
            <div className="w-full h-2 bg-gray-800 mb-10 border border-black">
              <div 
                className="h-full bg-mint-start transition-all duration-500 ease-out shadow-[0_0_10px_#A0F0E6]"
                style={{ width: `${((currentQIndex + 1) / QUESTIONS.length) * 100}%` }}
              ></div>
            </div>

            <h2 className="font-display font-bold text-2xl md:text-3xl mb-8 text-white min-h-[80px]">
              {QUESTIONS[currentQIndex].text}
            </h2>

            <div className="grid grid-cols-1 gap-4">
              {QUESTIONS[currentQIndex].options.map((opt, idx) => (
                <button
                  key={idx}
                  onClick={() => handleOptionSelect(QUESTIONS[currentQIndex].id, opt.value, opt.scorePenalty)}
                  className="group flex items-center justify-between p-5 text-left bg-void border-2 border-gray-700 hover:border-mint-start hover:shadow-hard transition-all duration-200 active:translate-y-1"
                >
                  <span className="font-sans font-medium text-off-white group-hover:text-white text-lg">
                    {opt.label}
                  </span>
                  <ChevronRight className="text-gray-600 group-hover:text-mint-start transition-colors" />
                </button>
              ))}
            </div>
          </div>
        )}

        {/* STATE 3: PROCESSING */}
        {stage === 'processing' && (
          <div className="flex flex-col items-center justify-center py-12 animate-in fade-in duration-500">
             <div className="relative w-24 h-24 mb-8">
              <div className="absolute inset-0 border-4 border-gray-800 rounded-full"></div>
              <div className="absolute inset-0 border-t-4 border-mint-start rounded-full animate-spin"></div>
              <div className="absolute inset-0 flex items-center justify-center">
                 <Activity className="text-mint-start w-8 h-8 animate-pulse" />
              </div>
            </div>
            <h3 className="font-mono text-xl text-mint-start animate-pulse text-center">
              {processingText}
            </h3>
            <div className="mt-4 font-mono text-xs text-gray-500">
              [ ENCRYPTING DATA STREAMS... ]
            </div>
          </div>
        )}

        {/* STATE 4 & 5: GATE & RESULTS (Shared Layout) */}
        {(stage === 'gate' || stage === 'results') && (
          <div className="relative w-full h-full">
            
            {/* THE GATE OVERLAY */}
            {stage === 'gate' && (
              <div className="absolute inset-0 z-50 flex flex-col items-center justify-center animate-in zoom-in duration-300">
                 {/* Progress Bar Top */}
                 <div className="absolute top-0 w-full mb-8">
                    <div className="flex justify-between items-center mb-2">
                        <span className="text-xs font-mono text-mint-start tracking-widest animate-pulse">ANALYSIS COMPLETE. REPORT READY.</span>
                        <span className="text-xs font-mono text-mint-start">95%</span>
                    </div>
                    <div className="w-full h-1 bg-gray-800">
                        <div className="w-[95%] h-full bg-mint-start shadow-[0_0_10px_#A0F0E6]"></div>
                    </div>
                 </div>

                 {/* Lock Icon */}
                 <div className="inline-block p-4 border-2 border-mint-start rounded-full bg-black mb-6 shadow-hard z-10">
                     <Lock className="w-8 h-8 text-mint-start" />
                 </div>

                 {/* Form Container */}
                 <div className="bg-[#15171c]/90 backdrop-blur-md border-2 border-gray-700 p-8 w-full max-w-md shadow-2xl relative">
                    <h2 className="font-display font-bold text-2xl text-white mb-2 text-center uppercase">IDENTITY VERIFICATION REQUIRED</h2>
                    <p className="text-gray-400 mb-6 font-mono text-xs text-center leading-relaxed">
                       Your efficiency roadmap has been generated. Where should we send the data?
                    </p>
                    
                    <div className="space-y-4">
                       <div>
                          <input 
                             type="text" 
                             value={leadForm.name}
                             onChange={(e) => setLeadForm({...leadForm, name: e.target.value})}
                             className="w-full bg-black border-2 border-gray-700 p-3 text-white focus:border-mint-start outline-none transition-colors placeholder-gray-600 font-sans"
                             placeholder="Full Name"
                          />
                       </div>
                       <div>
                          <input 
                             type="email" 
                             value={leadForm.email}
                             onChange={(e) => setLeadForm({...leadForm, email: e.target.value})}
                             onBlur={() => setTouched(prev => ({...prev, email: true}))}
                             className={`w-full bg-black border-2 ${touched.email && !leadForm.email.match(emailRegex) ? 'border-[#FF4444] animate-pulse' : 'border-gray-700'} p-3 text-white focus:border-mint-start outline-none transition-colors placeholder-gray-600 font-sans`}
                             placeholder="name@company.com"
                          />
                       </div>
                       <div>
                          <input 
                             type="text" 
                             value={leadForm.url}
                             onChange={(e) => setLeadForm({...leadForm, url: e.target.value})}
                             onBlur={() => setTouched(prev => ({...prev, url: true}))}
                             className={`w-full bg-black border-2 ${touched.url && !leadForm.url.match(urlRegex) ? 'border-[#FF4444] animate-pulse' : 'border-gray-700'} p-3 text-white focus:border-mint-start outline-none transition-colors placeholder-gray-600 font-sans`}
                             placeholder="yourcompany.com"
                          />
                       </div>
                       
                       <button 
                          onClick={handleGateSubmit}
                          disabled={!isFormValid}
                          className={`w-full py-4 mt-2 font-display font-bold text-sm uppercase tracking-wider transition-all duration-300 ${
                            isFormValid 
                              ? 'bg-gradient-to-r from-mint-start to-white text-black hover:shadow-hard hover:-translate-y-1' 
                              : 'bg-gray-800 text-gray-500 cursor-not-allowed opacity-50'
                          }`}
                       >
                          UNLOCK REPORT
                       </button>
                    </div>
                 </div>
              </div>
            )}

            {/* THE RESULTS (Blurred in Gate, Clear in Results) */}
            <div className={`transition-all duration-1000 ${stage === 'gate' ? 'filter blur-xl opacity-40 pointer-events-none select-none scale-95' : 'filter-none opacity-100 scale-100'}`}>
              <div className="text-center border-b-2 border-gray-800 pb-8 mb-8">
                 <div className="flex items-center justify-center gap-2 text-gray-500 mb-6">
                    <Terminal className="w-4 h-4" />
                    <span className="font-mono text-xs tracking-[0.3em] uppercase">SCALING FRACTURED</span>
                 </div>
                
                 <div className="mb-2 font-display font-bold text-sm text-gray-400 uppercase tracking-wider">ESTIMATED MONTHLY WASTE</div>
                 <div className="relative inline-block">
                    <h2 className="font-display font-bold text-6xl md:text-7xl tracking-tighter text-transparent bg-clip-text bg-gradient-to-br from-red-500 via-red-400 to-mint-start drop-shadow-2xl">
                       {formatCurrency(stage === 'gate' ? metrics.totalLeakage : displayLeakage)}
                    </h2>
                 </div>
                 
                 {/* Insight Sentence */}
                 <p className="mt-6 text-gray-300 max-w-lg mx-auto leading-relaxed">
                    You are burning <span className="text-white font-bold">{formatCurrency(metrics.totalLeakage)}</span> every month on friction. 
                    That is <span className="text-red-400 font-bold border-b border-red-500/50">{formatCurrency(metrics.annualLeakage)}</span> per year.
                 </p>
              </div>

              {/* Breakdown Grid */}
              <div className="grid grid-cols-2 gap-4 mb-8">
                 <div className="bg-[#15171c] border border-gray-800 p-4 rounded-sm text-center">
                    <div className="text-gray-500 text-xs uppercase font-mono mb-1">Operational Waste</div>
                    <div className="text-white font-display font-bold text-xl">{formatCurrency(metrics.operationalWaste)}</div>
                 </div>
                 <div className="bg-[#15171c] border border-gray-800 p-4 rounded-sm text-center">
                    <div className="text-mint-start text-xs uppercase font-mono mb-1">Missed Revenue</div>
                    <div className="text-white font-display font-bold text-xl">{formatCurrency(metrics.revenueUplift)}</div>
                 </div>
              </div>

              {/* Efficiency Score Bar */}
              <div className="mb-10">
                 <div className="flex justify-between text-xs font-mono text-gray-400 mb-2">
                    <span>EFFICIENCY SCORE</span>
                    <span className={metrics.efficiencyScore > 80 ? "text-green-500" : metrics.efficiencyScore > 50 ? "text-yellow-500" : "text-red-500"}>
                       {metrics.efficiencyScore}/100
                    </span>
                 </div>
                 <div className="w-full h-4 bg-gray-800 border border-black skew-x-[-10deg]">
                    <div 
                       className={`h-full transition-all duration-1000 ${metrics.efficiencyScore > 80 ? "bg-green-500" : metrics.efficiencyScore > 50 ? "bg-yellow-500" : "bg-red-500"}`}
                       style={{ width: `${metrics.efficiencyScore}%` }}
                    ></div>
                 </div>
              </div>

              <div className="text-center space-y-4">
                <h4 className="font-display font-bold text-3xl text-white uppercase">Stop the bleed.</h4>
                
                <Button onClick={onBookAudit} className="w-full !py-5 !text-lg shadow-[0_0_20px_rgba(160,240,230,0.3)] hover:shadow-[0_0_30px_rgba(160,240,230,0.5)]">
                  Book Quick Strike Audit
                </Button>

                <p className="text-xs text-gray-500 font-mono mt-4">
                   FULL BREAKDOWN WILL BE ENCRYPTED AND SENT TO {leadForm.email || 'YOUR INBOX'}.
                </p>
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};

export default Diagnostic;